#! /usr/bin/bash

function run {
   if (command -v $1 && ! pgrep $1); then
     $@&
   fi
}

run xwallpaper --zoom /home/mean/.config/BetterThanYour/wallpapers/austronaut-dark.jpg
run picom --config  ~/.config/picom.conf -b --experimental-backends
run setxkbmap -layout "us,gr" -option "grp:win_space_toggle"
run lxqt-policykit-agent
run dunst
run /opt/lights-on/lightsOn.sh
# run xautolock -time 5 -locker "dm-tool lock"
# run xautolock -detectsleep -time 10 -locker "~/.config/awesome/lockscreen"
run xcape -e 'Super_L=Super_L|P'
run dwmblocks
run xrdb ~/.config/space-vim-dark/terminal/space-vim-dark.xresources

dwm >> ~/.config/dwm/dwm.log
