#! /usr/bin/bash

function run {
   if (command -v $1 && ! pgrep $1); then
     $@&
   fi
}

run nitrogen --restore
run picom --config  ~/.config/picom.conf -b --experimental-backends
run setxkbmap -layout "us,gr" -option "grp:win_space_toggle"
run lxqt-policykit-agent
# run xautolock -detectsleep -time 10 -locker "~/.config/awesome/lockscreen"
# run msm_notifier
# run nm-applet
run dunst
run xautolock -time 5 -locker "dm-tool lock"
run xcape -e 'Super_L=Super_L|Control_L|Escape'
run thunar --daemon
run pa-applet
# run pamac-tray
run dwmblocks
run xrdb ~/.Xdefaults

dwm >> ~/.config/dwm/dwm.log
